// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    prettyPrint();
    return $('#comments-switch').click(function() {
      return $('.comment').fadeToggle();
    });
  });

}).call(this);
